baseurl = "/"
languageCode = "en-us"
title = "Kanteron Systems blog in English"
theme = "hugo-theme-casper"
#disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = "UA-51273041-2"
# Define how many posts should appear on a site
paginate = 10
canonifyurls = true

[params]
  description = "news and comments"
  cover = "images/cover.jpg"
  author = "Kanteron Systems"
  authorlocation = "Valencia | Madrid | NY | London"
  authorwebsite = "http://www.kanteron.com"
  bio= "Precision Medicine at the Point of Care"
  logo = "images/logo.png"
  googleAnalyticsUserID = "UA-51273041-2"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = "http://feeds.feedburner.com/..."
  githubName = "KanteronSystems"
  twitterName = "kanteron"
  # facebookName = ""
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  [params.social]
    twitter = "kanteron"

  [[menu.main]]
    name = "Blog"
    weight = -120
    identifier = "blog"
    url = "https://blogen.kanteron.com"

  [[menu.main]]
    name = "Website"
    weight = -110
    identifier = "web"
    url = "https://www.kanteron.com"
